import logging
class IncorrectFilePathError(Exception): ...
class PositionalArgError(Exception): ...
class IncompatableArgsError(Exception): ...
class IncorrectArgsError(Exception): ...
class UnknownVars(Exception): ...
class CannotOverride(Exception): ...
class UnknownError(Exception): ...
